- id: '1763877250924'
  alias: Kaiden Light Remote
  description: ''
  triggers:
  - domain: mqtt
    device_id: 8d32bbf31da97923277d779e9cc5d5f3
    type: action
    subtype: 'on'
    trigger: device
  conditions: []
  actions:
  - if:
    - condition: device
      type: is_on
      device_id: ea21b200db2b429e5c19341d516efaab
      entity_id: 07ece1ddae68d03d0f4d097dd296cf1f
      domain: light
    then:
    - action: scene.turn_on
      metadata: {}
      data: {}
      target:
        entity_id: scene.brighten_kaiden_bedroom
    else:
    - action: light.turn_on
      metadata: {}
      data:
        color_temp_kelvin: 2000
        brightness_pct: 1
      target:
        device_id:
        - 63b35d6ddbe9b5e25359fcfe3b3169ad
        - ea21b200db2b429e5c19341d516efaab
  mode: single
- id: '1763877373794'
  alias: 'Kaiden Light Remote: Off'
  description: ''
  triggers:
  - domain: mqtt
    device_id: 8d32bbf31da97923277d779e9cc5d5f3
    type: action
    subtype: 'off'
    trigger: device
  conditions: []
  actions:
  - action: light.turn_off
    metadata: {}
    data: {}
    target:
      entity_id:
      - light.smart_light_rgbcw_7
      - light.smart_light_rgbcw_8
  mode: single
- id: '1763946602731'
  alias: Kaiden Remote (Local)
  description: ''
  triggers:
  - domain: mqtt
    device_id: 8d32bbf31da97923277d779e9cc5d5f3
    type: action
    subtype: 'on'
    trigger: device
  conditions: []
  actions:
  - if:
    - condition: device
      type: is_on
      device_id: 98a2bc95b4b399648fd982a117ce7ddb
      entity_id: 1e2813efdc92e1ccadfd330bd4a3e2c7
      domain: light
    then:
    - action: scene.turn_on
      metadata: {}
      data: {}
      target:
        entity_id:
        - scene.brighten_kaiden_room_local
    else:
    - action: light.turn_on
      metadata: {}
      data:
        color_temp_kelvin: 2000
        brightness_pct: 1
      target:
        entity_id:
        - light.kaiden_bedroom_ceiling_interior_local
        - light.kaiden_bedroom_ceiling_exterior_local
  mode: single
- id: '1763946969493'
  alias: 'Kaiden Remote: Off (Local)'
  description: ''
  triggers:
  - domain: mqtt
    device_id: 8d32bbf31da97923277d779e9cc5d5f3
    type: action
    subtype: 'off'
    trigger: device
  conditions: []
  actions:
  - action: light.turn_off
    metadata: {}
    data: {}
    target:
      entity_id:
      - light.kaiden_bedroom_ceiling_interior_local
      - light.kaiden_bedroom_ceiling_exterior_local
  mode: single
- id: '1764938657332'
  alias: Turn off when no presence
  description: ''
  triggers:
  - type: not_occupied
    device_id: 1bb901dcd8f7a0a167d283f0552517bd
    entity_id: 42b2581acfd7812af22eee43b073dc03
    domain: binary_sensor
    trigger: device
  conditions:
  - condition: device
    type: is_on
    device_id: 2888a09df65f469e2c85d299782d7f25
    entity_id: 90a9708a4fd66d5d22a3679daaa16420
    domain: light
  actions:
  - type: turn_off
    device_id: 2888a09df65f469e2c85d299782d7f25
    entity_id: 90a9708a4fd66d5d22a3679daaa16420
    domain: light
  mode: single
- id: '1764938726674'
  alias: Turn on bathroom ceiling when occupied
  description: ''
  triggers:
  - type: occupied
    device_id: 1bb901dcd8f7a0a167d283f0552517bd
    entity_id: 42b2581acfd7812af22eee43b073dc03
    domain: binary_sensor
    metadata:
      secondary: false
    trigger: device
  conditions:
  - condition: device
    type: is_off
    device_id: 2888a09df65f469e2c85d299782d7f25
    entity_id: 90a9708a4fd66d5d22a3679daaa16420
    domain: light
  actions:
  - choose:
    - conditions:
      - condition: time
        after: 06:30:00
        before: '18:00:00'
      - type: is_illuminance
        condition: device
        device_id: 1bb901dcd8f7a0a167d283f0552517bd
        entity_id: a6620b56853b5aa3a7dc69672699d409
        domain: sensor
        below: 1300
      sequence:
      - action: scene.turn_on
        metadata: {}
        data: {}
        target:
          entity_id: scene.bathroom_ceiling_bright
    - conditions:
      - condition: time
        after: '18:00:00'
        before: '19:30:00'
      sequence:
      - action: scene.turn_on
        metadata: {}
        data: {}
        target:
          entity_id: scene.bathroom_ceiling_dim
    - conditions:
      - condition: time
        after: '19:30:00'
        before: 06:30:00
      sequence:
      - action: scene.turn_on
        metadata: {}
        data: {}
        target:
          entity_id: scene.bathroom_ceiling_dark
  mode: single
