version: '3'
services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - /volume1/docker/homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    networks:
      - localnet
    ports:
        - 8123:8123
        # Sonos?
        - 1400:1400
    privileged: true
    depends_on:
      - mosquitto

  mosquitto:
    container_name: mosquitto
    # TODO: Health checks and user name + password can come later
    # environment:
    #   - MOSQUITTO_USER
    #   - MOSQUITTO_PASSWORD
    image: eclipse-mosquitto:2
    restart: unless-stopped
    networks:
      - localnet
    ports:
      - "1883:1883/tcp"
    volumes:
      - /volume1/docker/homeassistant/mosquitto/config:/mosquitto/config
      - /volume1/docker/homeassistant/mosquitto/data:/mosquitto/data
      - /volume1/docker/homeassistant/mosquitto/log:/mosquitto/log
    # Create new password on start
    # docker compose exec mosquitto mosquitto_passwd -b /mosquitto/config/pwfile $MOSQUITTO_USER $MOSQUITTO_PASSWORD
    # healthcheck:
    #   test: ["CMD", "mosquitto_sub", "-u", "$MOSQUITTO_USER", "-P", "$MOSQUITTO_PASSWORD", "-h", "localhost", "-t", "$$SYS/broker/uptime", "-i", "docker_health_check", "-C", "1"]
    #   interval: 1m
    #   timeout: 10s
    #   retries: 3

networks:
  localnet:
    driver: bridge
