version: "3"
services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - /volume1/docker/homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    networks:
      - localnet
    ports:
      - 8123:8123
      # Sonos?
      - 1400:1400
    privileged: true
    depends_on:
      - mosquitto

  mosquitto:
    container_name: mosquitto
    # TODO: Health checks and user name + password can come later
    # environment:
    #   - MOSQUITTO_USER
    #   - MOSQUITTO_PASSWORD
    image: eclipse-mosquitto:2
    restart: unless-stopped
    networks:
      - localnet
    ports:
      - "1883:1883/tcp"
    volumes:
      - /volume1/docker/homeassistant/mosquitto/config:/mosquitto/config
      - /volume1/docker/homeassistant/mosquitto/data:/mosquitto/data
      - /volume1/docker/homeassistant/mosquitto/log:/mosquitto/log
    # Create new password on start
    # docker compose exec mosquitto mosquitto_passwd -b /mosquitto/config/pwfile $MOSQUITTO_USER $MOSQUITTO_PASSWORD
    # healthcheck:
    #   test: ["CMD", "mosquitto_sub", "-u", "$MOSQUITTO_USER", "-P", "$MOSQUITTO_PASSWORD", "-h", "localhost", "-t", "$$SYS/broker/uptime", "-i", "docker_health_check", "-C", "1"]
    #   interval: 1m
    #   timeout: 10s
    #   retries: 3

  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: ghcr.io/koenkk/zigbee2mqtt
    restart: unless-stopped
    volumes:
      - ./zigbee2mqtt-data:/app/data
      # Not using USB
      # - /run/udev:/run/udev:ro
    networks:
      - localnet
    ports:
      # Frontend port
      - 8080:8080
    environment:
      - TZ=Asia/Singapore
    # devices:
      # Make sure this matched your adapter location
      # - /dev/serial/by-id/usb-Texas_Instruments_TI_CC2531_USB_CDC___0X00124B0018ED3DDF-if00:/dev/ttyACM0
    # group_add:
    #   - dialout
    user: 1027:100


networks:
  localnet:
    driver: bridge
