---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/

- Ready:
    - Speed test:
        href: http://fiftytblock.lan:8083/
        widgets:
          - type: speedtest
            url: http://fiftytblock.lan:8083/
            version: 2
            key: PZivTJHcrZXhx0IEtXiT1EJyLFcY0ubCOd39qJvic7876dc8
            # bitratePrecision: 3 # optional, default is 0
    - Synology NAS:
        href: https://fiftytblock.lan:5001/
    - Home Assistant:
        href: http://fiftytblock.lan:8123/
    - Paperless:
        href: http://fiftytblock.lan:8000/
        widgets:
          - type: paperlessngx
            url: http://fiftytblock.lan:8000/
            key: 1ae8ce55bdcb517e785a21434cb0da795610be7e

- WIP:
    - Frigate:
        href: http://fiftytblock.lan:5123/
